export const ADD_INGREDIENTS='ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS='REMOVE_INGREDIENTS';
export const SET_INGREDIENTS='SET_INGREDIENTS';
export const SET_ERROR='SET_ERROR';

export const PURCHASE_START='PURCHASE_ORDER';
export const SUCCESS_ORDER_DATA='SUCCESS_ORDER_DATA';
export const FAILED_ORDER_DATA='FAILED_ORDER_DATA';

export const ON_PURCHASE_INIT='PURCHASE_INIT';

export const FETCH_ORDERS_START='FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS='FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL='FETCH_ORDER_FAIL';